# The intent is to keep this updated as new stable versions are relased.
# Probably easiest if it matches dropshot
#   https://github.com/oxidecomputer/dropshot/blob/main/rust-toolchain.toml

[toolchain]
channel = "1.95.0"
components = ["clippy", "rustfmt"]
