name: license-check
permissions:
  contents: read

on:
  push:

jobs:
  license:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@master
    - name: Check License Header
      uses: apache/skywalking-eyes/header@7a3b6cc34c5980cede4407ffa06fe553a999245d
