name: license-check
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  license:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@master
    - name: Check License Header
      uses: apache/skywalking-eyes/header@21648e752a1dad42cb46b50b38e77f0a8f15219c
