name: Release

on:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Create GitHub Release
        uses: ncipollo/release-action@caacf56b56ba217c4eaf0a9deb59dbcdd12abfcd
        with:
          draft: ${{ github.event_name == 'pull_request' }}
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref_name, '-pre') }}
