name: Test JS

on:
  push:
    branches:
      - main
    paths:
      - "remix-auth-vapi/**"
  pull_request:
    paths:
      - "remix-auth-vapi/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: remix-auth-vapi
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: remix-auth-vapi/package-lock.json
      - run: npm ci
      - run: npm run fmt:check
      - run: npm run lint
      - run: npm test
